### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by natesire** [rtc-io/rtc#20]
/private/var/www/eyehawk.io/node_modules/rtc-capture/index.js:5
navigator.getUserMedia = navigator.getUserMedia ||
^

ReferenceError: navigator is not defined
    at Object.<anonymous> (/private/var/www/eyehawk.io/node_modules/rtc-capture/index.js:5:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/var/www/eyehawk.io/node_modules/rtc-media/index.js:1:77)
    at Module._compile (module.js:541:32)

**Comment by ubuntutest** [comment]
Same problem here, did you fixed it?

**Comment by teckays** [comment]
Bump

**Comment by silviapfeiffer** [comment]
Can you provide more information? How did you get to that error?

**Comment by charu11** [comment]
bump!

same issue here, any suggestions or fixes ?

**Comment by silviapfeiffer** [comment]
What browser did you use?
